[package]
name = "day06"
version = "0.1.0"
authors = ["John Warwick <jwarwick@gmail.com>"]

[dependencies]
util = {path = "../util"}
itertools = "0.7.9"
scan_fmt = "0.1.3"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
